version: '3.9'
x-render-ignore: true
services:
  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  redis_data:
